### ISSUE TITLE
Need Help with Setup (OS X Server)

### ISSUE THREAD

**Issue by K-MTG** [idolpx/WhoIsHome#1]
Hi,

I am interested in setting up a mobile presence solution that I can integrate with SmartThing's, either directly or via IFTTT.

I am a somewhat beginner at this so I would much appreciate help with the implementation. 

I am running OS X Server on my Mac mini that remains on 24/7. Here a few screenshots of what I configured so far:

<img width="615" alt="server settings" src="https://user-images.githubusercontent.com/19272528/32131674-1da86e54-bb69-11e7-8826-5120cb92658f.png">

I basically created a new domain, the wp. at the bottom. I am hosting DNS locally so the domain is running locally currently even though it is at wp.server.com

Here are the domain settings:
<img width="581" alt="server setting 1" src="https://user-images.githubusercontent.com/19272528/32131681-4edb87e0-bb69-11e7-96a4-5e303c67fecc.png">

And here are the advance settings, please let me know if I need to enable any of the options:
<img width="600" alt="server settings 2" src="https://user-images.githubusercontent.com/19272528/32131683-5b36f5b0-bb69-11e7-88fb-c638ce5fddcc.png">

Here are the files at the root:
<img width="578" alt="root" src="https://user-images.githubusercontent.com/19272528/32131688-794908d6-bb69-11e7-9b97-d2f03fce1197.png">

All I did so far is just download the GitHub files and place them in my root directory. I didn't edit anything or install nmap, curl, or composer. I wasn't sure I needed it since OS X server has built in PHP. 

Right now my root page is blank and if I go to my server/whoishome...I get a Not Found message.

It would be much appreciated if someone can walk me through this and get this working...I can also share this on the SmartThing's forum if I get this working...lots of users want a great home automation solution.

Much appreciated! 

Thanks

**Comment by idolpx** [comment]
If you are getting a blank page it is probably throwing a PHP error.  You do need composer to install the other PHP libraries that are used in the project.  I'm guessing that if you look in the PHP error log it will be complaining about those missing libraries.

Get composer installed and run the "composer install" command to get those libraries and see what it does after that.  Then we can move to the next step of getting nmap and curl installed.

**Comment by idolpx** [comment]
Also... please pull the latest updates.  I have made some modifications.  :)

**Comment by K-MTG** [comment]
Thanks so much for the follow up! Will give this a shot and will let you know...do you know if I can communicate directly with SmartThings?

Or else I plan to have it send an email and then I will use IFTTT to communicate with SmartThing's. 

I was trying this direct solution on the SmartThings forum but didn't get it to work: https://community.smartthings.com/t/wi-fi-presence-app/103203/2

Should I follow these steps to install Composer: https://www.abeautifulsite.net/installing-composer-on-os-x

**Comment by idolpx** [comment]
I don't have a SmartThings device so I won't be much help there but I don't see why you couldn't have my script trigger the script that was mentioned in that post if it works.  It is already setup to send an email.  But it could really do just about anything.

Yes... use the instructions there for getting composer installed and working.
