### ISSUE TITLE
Upon running curl command, always returns out of disk space.

### ISSUE THREAD

**Issue by doubleangels** [idolpx/WhoIsHome#3]
`curl -L --max-redirs 999 http://localhost/WhoIsHome/cron.php` always returns "Out of disk space!". Navigating to the debug page produces the same error.

**Comment by idolpx** [comment]
Are you running this on a Windows, Linux or OSX server?
Is the drive it is installed on a remote file system?

**Comment by doubleangels** [comment]
Debian and Ubuntu Linux, sorry. It's a cloud machine so I'm running the commands over SSH.
